### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by benedikt-budig** [plotly/jupyter-dash#110]
It looks like there have been merged a few very helpful fixes and improvements, namely:
- https://github.com/plotly/jupyter-dash/pull/105
- https://github.com/plotly/jupyter-dash/pull/94
- https://github.com/plotly/jupyter-dash/pull/89

Some recently opened issues (e.g. https://github.com/plotly/jupyter-dash/issues/108, https://github.com/plotly/jupyter-dash/issues/103, https://github.com/plotly/jupyter-dash/issues/106) seem to be already fixed on `master`, but are still coming up because the fixes are not released yet.

@alexcjohnson @chriddyp @T4rk1n Would you consider releasing the current state as `0.4.3` to Pypi? I'm sure it would be appreciated a lot by the community; see also https://github.com/plotly/jupyter-dash/pull/89#issuecomment-1276247786.

**Comment by severinsimmler** [comment]
+1

**Comment by ptr33** [comment]
Hi,
I can confirm that the latest changes did solve the issue on my side described in https://github.com/plotly/jupyter-dash/issues/106 for refernce see the docker image https://github.com/ptr33/Jupyterlab/tree/jupyter-dash

To see this fixed, start it by using
```
docker run --rm -it -p 8888:8888 ghcr.io/ptr33/jupyterlab:jupyter-dash
```
and open http://localhost:8888/jupyter 

The latest released version (ghcr.io/ptr33/jupyterlab) failed for me with 'port already in use' on hot reloading and rerunning app.run_server().

Therefore please @alexcjohnson @chriddyp @T4rk1n would you consider releasing the current state?

Thank you
ptr33

**Comment by Darynh** [comment]
+1 - any news on the next release ?

In the mean time, I've been able to download latest `master` in a conda environment through the following
```
conda install pip git
pip install git+https//github.com/plotly/jupyter-dash.git
```

**Comment by jonasvdd** [comment]
+1 - I would love a new release - as I've now fixated the `werkzeug` version of https://github.com/predict-idlab/plotly-resampler/issues/123

However, there is a known security bug in `werkzeug<2.2.3` https://github.com/predict-idlab/plotly-resampler/pull/174

**Comment by imichaelmoore** [comment]
https://github.com/predict-idlab/plotly-resampler/pull/174 is waiting on a test to ensure the newer werkzeug doesn't cause a performance regression.  Hopefully it doesn't and will enable a swift release :)

+1 on a new release here too!

**Comment by jvdd** [comment]
+1 - for the same reason as @jonasvdd & @imichaelmoore 

Would really appreciate if any of @alexcjohnson @chriddyp @T4rk1n would consider making a new release :pray:

**Comment by Jamesong7822** [comment]
+1

**Comment by mcstarioni** [comment]
+1

**Comment by alexcjohnson** [comment]
Hey all, sorry for the silence here - we’re actually working to merge this functionality into the main Dash package https://github.com/plotly/dash/pull/2530 - after which this whole package will be obsolete.

**Comment by oegedijk** [comment]
@alexcjohnson in the meantime maybe at least do this release with the fixes? (two minutes of work to help a lot of users, seems like a fine investment?)

**Comment by T4rk1n** [comment]
@oegedijk This repo has been merged with Dash and is now obsolete. Please use Dash version 2.11.1 instead.
