### ISSUE TITLE
`jupyter_mode = inline` fails where `external` and `tab` work

### ISSUE THREAD

**Issue by Benfeitas** [plotly/jupyter-dash#124]
I'm running jupyterlab and Dash and trying to show all figures inline. Strangely, when I do `app.run(jupyter_mode='inline')` a blank box opens beneath the cell and renders nothing, whereas when I use `app.run(jupyter_mode='external)` or `app.run(jupyter_mode='tab')` I can see the plots normally. 

Any suggestions on how to overcome this?

dash=2.11.1
jupyter-dash=0.4.2
python=3.9.12

**Comment by alexcjohnson** [comment]
@Benfeitas as of Dash v2.11 there's no need for the separate jupyter-dash package anymore, see https://dash.plotly.com/dash-in-jupyter. Please give the new version a try and if you run into any issues you can report them in the Dash repo or discuss at https://community.plotly.com/
