### ISSUE TITLE
Not working properly when executing as python script on Jupyter terminal

### ISSUE THREAD

**Issue by guoqianglan** [plotly/jupyter-dash#13]
Hi, thanks for the great work. It is working perfectly when executing on Jupyterlab notebook. However, when I tried to execute it as a python script on Jupyterlab terminal, the dash app page deployed on 'http://localhost:8888/proxy/8050' was blocked on 'Loading...'.
![image](https://user-images.githubusercontent.com/6219989/82744526-bb5e9c00-9d47-11ea-9613-ccce2b48792f.png)

 I know this is an issue between 'Dash' and 'jupyter-server-proxy', not related to 'jupyter-dash'. But it seems to be a small fix to enable 'jupyter-dash'  magic work with a python script as well? This is very useful when we want to use 'Jupyter Server Proxy'  to run dash app alongside our notebooks and provide authenticated web access to them with jupyterhub [https://jupyter-server-proxy.readthedocs.io/en/latest/server-process.html](https://jupyter-server-proxy.readthedocs.io/en/latest/server-process.html).

Thanks

**Comment by jonmmease** [comment]
Hi @guoqianglan, thanks for the encouraging words. Glad it's working for you well in the notebook!

When you use jupyter-dash in a non-ipython context (like the plain Python terminal in JupyterLab), it is intended to behave like the regular `Dash` class.

I don't think it will be possible to include the jupyter-dash magic proxy/url detection from the command line becuase this relies on having the front-end extension (`jupyterlab-dash` in this case) report the server URL and subpath info back to the Python kernel using Jupyter Comms.

But, you should be able to make it work from the command-line by passing config arguments to the `Dash`/`JupyterDash` constructor.  In particular, you'll need to pass the `requests_pathname_prefix` argument.  You should be able to lookup what `JupyterDash` detected that this should be by printing out the `app.config` dictionary after serving the app with `run_server`.

When you call `run_server` with `mode="external"` in the notebook, note the URL that it prints out. This is the same URL (modulo port number) that you'll need to visit when you run from the command line (The command line doesn't know about the proxy so it won't print out the correct URL).

Hope that helps!

**Comment by guoqianglan** [comment]
@jonmmease Thank you so much. With your suggestion, I am able to make it work. I did something as follows,
1. Create a python file, `app.py`, including
```python
...
args = parse_args(sys.argv[1:])
app = JupyterDash(__name__, requests_pathname_prefix='/proxy/{}/'.format(args.port))
...
app.run_server(port=args.port)
```
In Jupyterhub, we can use `requests_pathname_prefix='/user-redirect/proxy/{}/'.format(args.port)`

2. With 'jupyter-server-proxy' installed, modify the `~/.jupyter/jupyter_notebook_config.py`
```
c.ServerProxy.servers = {
  'dash-map': {
    'command': ['python', '<your_path>/app.py', '--port', '{port}'],
  }
}
```
3. Restart the Jupyterlab, now you can see 'dash-map' on your launcher. Click it and enjoy your app!
![Capture](https://user-images.githubusercontent.com/6219989/82856930-72d8e700-9edd-11ea-98b5-fb414ac0b6ae.PNG)

Cheers
