### ISSUE TITLE
Unable to use infer_jupyter_proxy_config with jupyterhub 

### ISSUE THREAD

**Issue by qih08** [plotly/jupyter-dash#28]
Hi!

I'm having trouble getting jupyter-dash to work with jupyterhub.

The base environment that jupyterhub is running in has jupyter_server_proxy enabled (shows up when the jupyter serverextensions are listed). The kernel has jupyter-dash installed. I'm primarily interested in getting it to work with classic notebooks, but I tried it in lab and it didn't work either (same error).

Running:
`JupyterDash.infer_jupyter_proxy_config()`
results in the following error:
```
OSError: Unable to communicate with the jupyter_dash notebook or JupyterLab 
extension required to infer Jupyter configuration.
```

I tried adding the
```
from jupyter_dash.comms import _send_jupyter_config_comm_request
_send_jupyter_config_comm_request()
```
from  #17, but no luck there. 

Any advice for how to debug further?

**Comment by mschenone** [comment]
Hey, I am facing the same issue.

_send_jupyter_config_comm_request() does not help
jupyter_dash.comms._jupyter_config returns {}

Here it is my setup:

jupyter                      1.0.0
jupyter-client               6.1.7
jupyter-console              6.1.0
jupyter-core                 4.7.0
jupyter-dash                 0.3.1
jupyter-server-proxy         1.5.0
jupyter-telemetry            0.0.4
jupyterhub                   1.1.0
jupyterhub-ldapauthenticator 1.3.0
jupyterlab                   2.2.6
jupyterlab-dash              0.1.0a3
jupyterlab-git               0.10.0
jupyterlab-pygments          0.1.2
jupyterlab-server            1.2.0


JupyterLab v2.2.6
Known labextensions:
   app dir: /jupyter/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/debugger v0.3.2  enabled  OK
        @jupyterlab/git v0.20.0  enabled  OK
        @jupyterlab/server-proxy v2.1.1  enabled  OK
        bamboolib v1.16.0  enabled  OK
        jupyterlab-dash v0.3.0  enabled  OK
        jupyterlab-plotly v4.9.0  enabled  OK
        jupyterlab-system-monitor v0.6.0  enabled  OK
        jupyterlab-topbar-extension v0.5.0  enabled  OK
        nbdime-jupyterlab v2.0.0  enabled  OK
        plotlywidget v4.9.0  enabled  OK
        qgrid2 v1.1.3  enabled  OK

Any suggestion for further investigation? Thanks a lot!

**Comment by chadaeschliman** [comment]
Not sure if this will help, but I found awhile ago after some experimentation that I had to split the jupyter-dash code into separate notebook cells.

First cell:
```    
from jupyter_dash.comms import _send_jupyter_config_comm_request
_send_jupyter_config_comm_request()
```
Second cell:
```
from jupyter_dash import JupyterDash as Dash
[other dash imports]
```
I expect there's a timing issue where there needs to be some gap after `_send_jupyter_config_comm_request()` before doing anything else.

**Comment by qih08** [comment]
It worked after I installed jupyter-dash into the base environment as well! No need for _send_jupyter_config_comm_request()

**Comment by ValarLee** [comment]
> It worked after I installed jupyter-dash into the base environment as well! No need for _send_jupyter_config_comm_request()

Hi , I have met the same problem .
what means "installed jupyter-dash into the base environment "

**Comment by Folongton** [comment]
> It worked after I installed jupyter-dash into the base environment as well! No need for _send_jupyter_config_comm_request()

Same here

**Comment by Folongton** [comment]
> > It worked after I installed jupyter-dash into the base environment as well! No need for _send_jupyter_config_comm_request()
> 
> Hi , I have met the same problem .
> what means "installed jupyter-dash into the base environment "

Google " What is base environment"

**Comment by garmenz** [comment]
> It worked after I installed jupyter-dash into the base environment as well! No need for _send_jupyter_config_comm_request()

Still doesn't work after installed installed jupyter-dash into the base environment, still gets the OS error

**Comment by cmosguy** [comment]
None of this worked for me

**Comment by BO-Rens** [comment]
Did the trick.  Thanks
