### ISSUE TITLE
Unable to run Jupyter-dash with JupyterHub | Unable to communicate with the jupyter_dash notebook or JupyterLab

### ISSUE THREAD

**Issue by JavierHernandezMontes** [plotly/jupyter-dash#44]
When I try to run jupyter-dash in jupyterhub I get the following error:

```
from jupyter_dash import JupyterDash
JupyterDash.infer_jupyter_proxy_config()
```

---------------------------------------------------------------------------
_OSError                                   Traceback (most recent call last)
<ipython-input-3-aac7d3a89f28> in <module>
----> 1 JupyterDash.infer_jupyter_proxy_config()

/opt/conda/lib/python3.7/site-packages/jupyter_dash/jupyter_app.py in infer_jupyter_proxy_config(cls)
     71         else:
     72             # Assume classic notebook or JupyterLab
---> 73             _request_jupyter_config()
     74 
     75     def __init__(self, name=None, server_url=None, **kwargs):

/opt/conda/lib/python3.7/site-packages/jupyter_dash/comms.py in _request_jupyter_config(timeout)
     61             # give up
     62             raise EnvironmentError(
---> 63                 "Unable to communicate with the jupyter_dash notebook or JupyterLab \n"
     64                 "extension required to infer Jupyter configuration."
     65             )

OSError: Unable to communicate with the jupyter_dash notebook or JupyterLab 
extension required to infer Jupyter configuration._

The version of JupyterLab is v2.2.9 and I am using  jupyterlab-dash v0.3.0. 

When I try to use the archived version (jupyterlab_dash) it works fine, example: 

```
import jupyterlab_dash
import dash
import dash_html_components as html
​
viewer = jupyterlab_dash.AppViewer()
​
app = dash.Dash(__name__)
​
app.layout = html.Div('Hello World')
​
viewer.show(app)
```
![image](https://user-images.githubusercontent.com/25748527/99258046-42349300-2818-11eb-95a3-c5742eda0aab.png)

Given the error from above if I use the new version jupyter_dash, and If I run _app.run_server("jupyterlab")_ nothing shows

**Comment by GuySerfaty** [comment]
Seeing it also with lab 3.X, @JavierHernandezMontes  why did you close this issue?
