### ISSUE TITLE
Any plans to add support for jupyterlab 3.0 ?

### ISSUE THREAD

**Issue by JessicaBarh** [plotly/jupyter-dash#50]
the latest version of jupyter-dash does not see to work on jupyterlab 3. Are there any plans for this?

**Comment by nicolaskruchten** [comment]
Yes, definitely, just haven't gotten around to it just yet :)

**Comment by jonmmease** [comment]
Done in https://github.com/plotly/jupyter-dash/pull/51 and released in 0.4.0
