### ISSUE TITLE
can't run JupyterDash.infer_jupyter_proxy_config() in Jupyterhub

### ISSUE THREAD

**Issue by statiksof** [plotly/jupyter-dash#62]
I am not able to run ` JupyterDash.infer_jupyter_proxy_config()` in Jupyterhub. There is no error message, cell remains in busy state without any output. Do you have any idea?

* `app.run_server()` returns `127.0.0.1:8005` which will not work from outside 
* `app.run_server("mode=jupyterlab")` also won't work 
*  I also see in the browser console: `blocked mixed content: the page was loaded over HTTPS, but requested an insecure frame 'http://ip:8050/'. This request has been blocked; the content must be served over HTTPS.`

only thing working is opening the ip:8050 in another tab and I can see the dashboard.

**Comment by LukaPitamic** [comment]
Same here. We want to develop dash apps in jupyterlab hub (tljh).
![image](https://user-images.githubusercontent.com/34914144/144392227-9ef76464-3bdb-491b-b6b6-3c475482e19d.png)

**Comment by datainvestor** [comment]
Any progress on this issue?

**Comment by LukaPitamic** [comment]
me waiting also ;)

**Comment by gravelrider** [comment]
Same here.
Are there any updates on this issue?

**Comment by edmundhighcock** [comment]
I have  a docker MWE to replicate this:

```
```

**Comment by psavery** [comment]
It appears that about a year ago, ipykernel [changed several functions into coroutines](https://github.com/ipython/ipykernel/pull/632). That includes [this function being called in jupyter-dash](https://github.com/plotly/jupyter-dash/blob/a6b9adf54f71f9d461a8aef6d64984b8ef61760c/jupyter_dash/comms.py#L69).

Thus, that function call needs to be changed to maybe something like this:
```python
loop = asyncio.get_running_loop()
loop.run_until_complete(kernel.do_one_iteration())
```

That would hopefully fix it.

For now, I'm just downgrading `ipykernel` to 5.5.4 (the version immediately before that change) and the jupyter dash example seems to work...
