### ISSUE TITLE
Jupyter-Dash no longer working in Jupyterlab 3.1.1?

### ISSUE THREAD

**Issue by cammclean182** [plotly/jupyter-dash#65]
Are there issues with Jupyter-Dash in Jupyterlab 3.1.1?

I've just created a new venv and installed the latest jupyterlab, dash, Jupyter-dash libraries. I'm trying to run the code from the example notebook in the repo.

When i run the cell for  `JupyterDash.infer_jupyter_proxy_config()` i get the error:

> c:\jupyter\venv\lib\site-packages\jupyter_dash\comms.py:69: RuntimeWarning: coroutine 'Kernel.do_one_iteration' was never awaited
  kernel.do_one_iteration()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Then the notebook becomes unresponsive until i restart the kernel.

![image](https://user-images.githubusercontent.com/16827877/127771174-06fb7a39-d372-40e0-88ca-dce360a2cb3a.png)

Package versions are:

![image](https://user-images.githubusercontent.com/16827877/127771261-de5d1225-bd75-446f-b17e-c655095d4c6a.png)

The extension looks like it was installed correctly. I installed jupyter-dash and then did a lab rebuild.

![image](https://user-images.githubusercontent.com/16827877/127771297-3fa9ce20-e4a7-4f6a-bf87-8a6472d1a8ab.png)

I've tried running this on my pc as well as in a docker container on my NAS. Both get the same issues.

**Comment by cammclean182** [comment]
Apologies i got this working. Thanks

**Comment by andrewsali** [comment]
@cammclean182 what was your solution?
