### ISSUE TITLE
No module named 'jupyter-dash'

### ISSUE THREAD

**Issue by Dwingkak** [plotly/jupyter-dash#90]
I encountered this problem when I was trying to run `from jupyter_dash import JupyterDash` in both jupyter notebook and jupyter lab. 

OS: Windows 10
python version: 3.8.13
Installed packages:  

Package&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Version

ansi2html&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 0.0.0
anyio&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3.6.1
appnope&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 0.1.3
argon2-cffi&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 21.3.0
argon2-cffi-bindings&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 21.2.0
asttokens&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2.0.5
async-generator&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1.10
attrs&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;21.4.0
Babel&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2.10.1
backcall &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0.2.0
backports.functools-lru-cache&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1.6.4
beautifulsoup4  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              4.11.1
bleach        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                5.0.0
Bottleneck        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            1.3.4
Brotli         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;               1.0.9
brotlipy          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            0.7.0
certifi           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            2022.5.18.1
cffi               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           1.15.0
chardet           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           4.0.0
charset-normalizer     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       2.0.12
click           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              8.1.3
colorama         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             0.4.4
cryptography    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              37.0.1
dash            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              2.4.1
dash-bootstrap-components  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   1.1.0
dash-core-components     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    2.0.0
dash-html-components     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     2.0.0
dash-renderer      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           1.9.1
dash-table         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           5.0.0
debugpy             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          1.6.0
decorator          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           5.1.1
defusedxml        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            0.7.1
deprecation        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           2.1.0
entrypoints        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           0.4
executing           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          0.8.3
fastjsonschema         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       2.15.3
Flask              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           2.1.2
Flask-Compress      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          0.0.0
flit_core         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            3.7.1
future            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            0.18.2
gunicorn         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             20.1.0
idna        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                  3.3
importlib-metadata      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     4.11.4
importlib-resources     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      5.7.1
ipykernel       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              6.13.1
ipython          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             8.4.0
ipython-genutils       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      0.2.0
itsdangerous         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         2.1.2
jedi            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              0.18.1
Jinja2         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;               3.1.2
joblib           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             1.1.0
json5             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            0.9.6
jsonschema      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              4.6.0
jupyter-client       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         7.3.3
jupyter-core        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          4.10.0
jupyter-dash        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          0.4.2
jupyter-packaging     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        0.12.0
jupyter-server     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           1.17.0
jupyterlab      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              3.4.2
jupyterlab-pygments   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        0.2.2
jupyterlab-server    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         2.14.0
MarkupSafe       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             2.1.1
matplotlib-inline        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     0.1.3
mistune           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            0.8.4
mkl-fft            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           1.3.1
mkl-random          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          1.2.2
mkl-service         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          2.4.0
nbclassic         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            0.3.7
nbclient       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;               0.6.4
nbconvert        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             6.5.0
nbformat          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            5.4.0
nest-asyncio       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           1.5.5
notebook          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            6.4.11
notebook-shim      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           0.1.0
numexpr          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             2.8.1
numpy         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                1.22.3
packaging            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         21.3
pandas            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            1.4.2
pandocfilters     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            1.5.0
parso            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             0.8.3
pexpect          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             4.8.0
pickleshare      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             0.7.5
pip            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;               21.2.2
plotly          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              5.8.0
prometheus-client      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       0.14.1
prompt-toolkit       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         3.0.29
psutil          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              5.9.1
ptyprocess        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            0.7.0
pure-eval           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          0.2.2
pycparser         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            2.21
Pygments           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           2.12.0
pyOpenSSL      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;               22.0.0
pyparsing        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             3.0.9
pyrsistent         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           0.18.1
PySocks           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            1.7.1
python-dateutil      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         2.8.2
pytz              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            2022.1
pywin32         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              303
pywinpty            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          2.0.2
pyzmq            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             23.1.0
requests        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              2.27.1
retrying         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             1.3.3
scikit-learn    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              1.0.2
scipy            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             1.7.3
Send2Trash    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                1.8.0
setuptools   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                 61.2.0
six             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              1.16.0
sniffio           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            1.2.0
soupsieve         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            2.3.1
stack-data         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           0.2.0
tenacity            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          8.0.1
terminado     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                0.15.0
testpath              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        0.6.0
threadpoolctl      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           2.2.0
tinycss2             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         1.1.1
tomlkit           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            0.11.0
tornado        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;               6.1
traitlets        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             5.2.2.post1
urllib3         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              1.26.9
wcwidth        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;               0.2.5
webencodings          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        0.5.1
websocket-client       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       1.3.2
Werkzeug          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            2.1.2
wheel           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              0.37.1
win-inet-pton       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          1.1.0
wincertstore         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         0.2
zipp                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          3.8.0

**Comment by alexcjohnson** [comment]
Possibly a different Python env running within Jupyter vs outside it? You can try in a notebook cell `!pip install jupyter-dash` (or `!pip list` in a cell to see what packages you have installed in that environment)

**Comment by Dwingkak** [comment]
> Possibly a different Python env running within Jupyter vs outside it? You can try in a notebook cell `!pip install jupyter-dash` (or `!pip list` in a cell to see what packages you have installed in that environment)

Thank you for your prompt reply. The listed packages in my previous post are generated with `!pip list` within a jupyter notebook cell and jupyter-dash is in the list.

**Comment by alexcjohnson** [comment]
Oh interesting, looks like that's what happens in jupyter if there's an error during import. Though at least when I try it, that's what I see in jupyter lab but in a classic notebook I see the underlying error (if I manually add an error, since in my case this import works fine).

If you see this same message with no more detail in both environments, perhaps trying to import those in Python in a terminal would show the underlying error?

**Comment by Dwingkak** [comment]
> Oh interesting, looks like that's what happens in jupyter if there's an error during import. Though at least when I try it, that's what I see in jupyter lab but in a classic notebook I see the underlying error (if I manually add an error, since in my case this import works fine).
> 
> If you see this same message with no more detail in both environments, perhaps trying to import those in Python in a terminal would show the underlying error?

I can import jupyter_dash in a python script without any error.

**Comment by Dwingkak** [comment]
> Hmph well now I can't replicate the module not found I saw once yesterday. Seems to me either it really is not found, or it's generating an error only in Jupyter.
> 
> To see if it's the former, you could import another pip-installed package both inside and outside jupyter and see if the package's `__file__` is the same in both cases.
> 
> To see if it's the latter, maybe wrap the import in a try/except?
> 
> ```python
> try:
>     from jupyter_dash import JupyterDash
> except Exception:
>     import traceback
>     print(traceback.format_exc())
> ```

I used the first method and found that my jupyter was running with the kernel of other env. I have solved the problem. Thank you for help me to troubleshoot the problem.
